const data ={
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            CountInStock: 10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Formal Pant',
            category:'Pants',
            image:'/images/p2.jpg',
            price:100,  CountInStock: 20,
            brand:'Nike',
            rating:4.0,
            numReviews:18,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:220,  CountInStock: 0,
            brand:'Addidas',
            rating:4.3,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Pant',
            category:'Pants',
            image:'/images/p4.jpg',
            price:120,  CountInStock: 15,
            brand:'Nike',
            rating:3.8,
            numReviews:15,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Addidas Pant Formal',
            category:'Pants',
            image:'/images/p5.jpg',
            price:150,  CountInStock: 12,
            brand:'Addidas',
            rating:4.5,
            numReviews:20,
            description:'high quality product',
        },
    ],
};
export default data;
